query GetLatestPost {
	allPost (limit : 1) {
		title
    feature
    _createdAt
    _updatedAt
		slug {
			current
		}
		tags
    contentRaw
		mainImage {
			image {
				asset {
					url
				}
			}
			alt
		}
	}
}
