query GetPostBySlug($slug: String!) {
  allPost (where: {slug: {current: {eq: $slug}}}) {
    _createdAt
    _updatedAt
    title
    feature
    slug {
      current
    }
    tags
    contentRaw
    mainImage {
      image {
        asset {
          url
        }
      }
      alt
      caption
    }
  }
}